### PR TITLE
fix(all): point package.json module from dist/es2015 back to dist/native-modules

### PR DESCRIPTION
**Pull request by 3cp**

### CODE REVIEW

**Comment by 3cp** [comment]
@bigopon can you help on the the circleci migration?

**Comment by bigopon** [comment]
Sure ill do it later today. Thanks for this PR @3cp

**Comment by 3cp** [comment]
This is the last es2015->native_modules fix.

**Comment by 3cp** [comment]
The circleci orb seems installing wrong jspm version, we need very old version. Anyone can update the orb to install `jspm@0.16.55` ?

```
orbs:
  v1: aurelia/v1@volatile
```

**Comment by 3cp** [comment]
Will try another PR to see if I can force it to pick up github actions.

**Pull request closed without merging**
